"""POSCAR writing from a pymatgen Structure.

The canonical ``POSCAR`` is always written — it is the session's *active*
structure that downstream tools (optimize / MD / VASP) auto-pick-up. An
optional labeled copy ``POSCAR_<formula>[_<tag>]`` is written for human
identification (e.g. ``POSCAR_Si_slab111``); the operation `tag` keeps artifacts
from different transforms from colliding on the same name. The POSCAR title line
(line 1) carries a "Generated by Materia" provenance stamp.
"""

from datetime import date
from pathlib import Path


def _provenance_comment(structure, tag: str | None) -> str:
    """Build the POSCAR title/line-1 comment: '<formula>[ <tag>] — Generated by Materia <date>'."""
    formula = structure.composition.reduced_formula
    label = f"{formula} {tag}".strip() if tag else formula
    return f"{label} — Generated by Materia {date.today().isoformat()}"


def write_poscar(
    structure,
    dest_dir: Path,
    name: str | None = None,
    *,
    tag: str | None = None,
    named_copy: bool = True,
) -> dict:
    """Write a Structure to ``POSCAR`` (+ an optional labeled copy) in `dest_dir`.

    Args:
        name: base label for the copy (defaults to the reduced formula).
        tag:  operation tag appended to the copy name and the provenance line,
              e.g. ``slab111`` → ``POSCAR_Si_slab111``.
        named_copy: when False, only the canonical ``POSCAR`` is written (used for
              VASP input folders, where the labeled copy is redundant — VASP reads
              plain POSCAR only).

    Returns a summary dict (status, formula, n_sites, lattice params, paths,
    files_written).
    """
    from pymatgen.io.vasp import Poscar

    formula = structure.composition.reduced_formula
    poscar = Poscar(structure, comment=_provenance_comment(structure, tag))

    poscar_path = dest_dir / "POSCAR"
    poscar.write_file(str(poscar_path))
    files_written = ["POSCAR"]

    named_path: Path | None = None
    if named_copy:
        base = name or formula
        label = f"{base}_{tag}" if tag else base
        named_path = dest_dir / f"POSCAR_{label}"
        poscar.write_file(str(named_path))
        files_written.append(named_path.name)

    return {
        "status":        "success",
        "formula":       formula,
        "n_sites":       len(structure),
        "lattice_a":     round(structure.lattice.a, 4),
        "lattice_b":     round(structure.lattice.b, 4),
        "lattice_c":     round(structure.lattice.c, 4),
        "poscar_path":   str(poscar_path),
        "named_path":    str(named_path) if named_path else None,
        "files_written": files_written,
    }
